name: Git checkout

description: A wrapper for actions/checkout with a custom git config

inputs:
  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    required: false
    default: 1

  ssh-key:
    required: false

runs:
  using: composite

  steps:
    - name: Set up custom git config
      shell: bash
      run: |
        git config --global core.compression 0
        git config --global http.postBuffer 1048576000
        git config --global http.lowSpeedLimit 512000
        git config --global http.lowSpeedTime 600
        git config --global core.packedGitLimit 2024m
        git config --global core.packedGitWindowSize 2024m
        git config --global pack.deltaCacheSize 2047m 
        git config --global pack.packSizeLimit 2047m 
        git config --global pack.windowMemory 2047m

    - name: Show config before checkout
      shell: bash
      run: |
        git config --global --list

    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ssh-key: ${{ inputs.ssh-key }}

    - name: Show config after checkout
      shell: bash
      run: |
        git config --global --list
